# fluentd/Dockerfile
FROM fluent/fluentd:v1.11.1-debian-1.0
#RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-rdoc", "--no-ri", "--version", "1.9.2"]
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--version", "4.1.1"]