apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  labels:
    app: opensearch
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opensearch
    helm:
      parameters:
      - name: replicas
        value: "1"
      values: |
        ingress:
          enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        path: /
        hosts:
          - elasticsearch.127.0.0.1.nip.io
        tls:
          hosts:
            - elasticsearch.127.0.0.1.nip.io

    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 1.7.4
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
