apiVersion: v1
kind: Pod
metadata:
  name: odfe-node1
spec:
  hostname: odfe-node1
  initContainers:
    - name: init-sysctl
      image: busybox:1.27.2
      command:
        - sysctl
        - -w
        - vm.max_map_count=262144
      securityContext:
        privileged: true
  containers:
    - name: es-master
      image: amazon/opendistro-for-elasticsearch:latest
      env:
      - name: NAMESPACE
        valueFrom:
           fieldRef:
              fieldPath: metadata.namespace
      - name: NODE_NAME
        valueFrom:
            fieldRef:
               fieldPath: metadata.name
      - name: CLUSTER_NAME
        value: myesdb
      - name: NUMBER_OF_MASTERS
        value: "2"
      - name: NODE_MASTER
        value: "true"
      - name: NODE_INGEST
        value: "true"
      - name: NODE_DATA
        value: "true"
      - name: HTTP_ENABLE
        value: "false"
      - name: ES_JAVA_OPTS
        value: -Xms256m -Xmx256m
      - name: PROCESSORS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: cluster.initial_master_nodes
        value: odfe-node1