apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logging-stacks.bytefusion.de
spec:
  group: bytefusion.de
  names:
    kind: LoggingStack
    listKind: LoggingStackList
    plural: logging-stacks
    singular: logging-stack
    shortNames:
      - bfls
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: integer
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false
      # A schema is required
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: integer

