apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  labels:
    group: security
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: third-party/ingress-nginx/v1.1.0
    repoURL: https://github.com/bfblog/efk-stack.git
    targetRevision: work
  syncPolicy:
    automated: {}