apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  labels:
    app-of-apps: logging
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/bfblog/efk-stack.git
    targetRevision: work
    path: applications/profiles/logging

    # directory
    directory:
      recurse: true
      
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Ignore differences at the specified json pointers
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
